# k-Fold Cross Validation

In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [25]:
# import data
dataset = pd.read_csv("Social_Network_Ads.csv")
dataset.head()

User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0          0
1  15810944    Male  35.0          20000.0          0
2  15668575  Female  26.0          43000.0          0
3  15603246  Female  27.0          57000.0          0
4  15804002    Male  19.0          76000.0          0

In [26]:
X = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, 4].values

print(X)
print(X.shape)
print("\n")
print(y)
print(y.shape)

[[  1.90000000e+01   1.90000000e+04]
 [  3.50000000e+01   2.00000000e+04]
 [  2.60000000e+01   4.30000000e+04]
 [  2.70000000e+01   5.70000000e+04]
 [  1.90000000e+01   7.60000000e+04]
 [  2.70000000e+01   5.80000000e+04]
 [  2.70000000e+01   8.40000000e+04]
 [  3.20000000e+01   1.50000000e+05]
 [  2.50000000e+01   3.30000000e+04]
 [  3.50000000e+01   6.50000000e+04]
 [  2.60000000e+01   8.00000000e+04]
 [  2.60000000e+01   5.20000000e+04]
 [  2.00000000e+01   8.60000000e+04]
 [  3.20000000e+01   1.80000000e+04]
 [  1.80000000e+01   8.20000000e+04]
 [  2.90000000e+01   8.00000000e+04]
 [  4.70000000e+01   2.50000000e+04]
 [  4.50000000e+01   2.60000000e+04]
 [  4.60000000e+01   2.80000000e+04]
 [  4.80000000e+01   2.90000000e+04]
 [  4.50000000e+01   2.20000000e+04]
 [  4.70000000e+01   4.90000000e+04]
 [  4.80000000e+01   4.10000000e+04]
 [  4.50000000e+01   2.20000000e+04]
 [  4.60000000e+01   2.30000000e+04]
 [  4.70000000e+01   2.00000000e+04]
 [  4.90000000e+01   2.80000000e+04]
 

In [27]:
# splitting the data into te Training set and Test set
from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
print(X_train)
print(X_train.shape)
print("\n")
print(X_test)
print(X_test.shape)
print("\n")
print(y_train)
print(y_train.shape)
print("\n")
print(y_test)
print(y_test.shape)

[[  4.40000000e+01   3.90000000e+04]
 [  3.20000000e+01   1.20000000e+05]
 [  3.80000000e+01   5.00000000e+04]
 [  3.20000000e+01   1.35000000e+05]
 [  5.20000000e+01   2.10000000e+04]
 [  5.30000000e+01   1.04000000e+05]
 [  3.90000000e+01   4.20000000e+04]
 [  3.80000000e+01   6.10000000e+04]
 [  3.60000000e+01   5.00000000e+04]
 [  3.60000000e+01   6.30000000e+04]
 [  3.50000000e+01   2.50000000e+04]
 [  3.50000000e+01   5.00000000e+04]
 [  4.20000000e+01   7.30000000e+04]
 [  4.70000000e+01   4.90000000e+04]
 [  5.90000000e+01   2.90000000e+04]
 [  4.90000000e+01   6.50000000e+04]
 [  4.50000000e+01   1.31000000e+05]
 [  3.10000000e+01   8.90000000e+04]
 [  4.60000000e+01   8.20000000e+04]
 [  4.70000000e+01   5.10000000e+04]
 [  2.60000000e+01   1.50000000e+04]
 [  6.00000000e+01   1.02000000e+05]
 [  3.80000000e+01   1.12000000e+05]
 [  4.00000000e+01   1.07000000e+05]
 [  4.20000000e+01   5.30000000e+04]
 [  3.50000000e+01   5.90000000e+04]
 [  4.80000000e+01   4.10000000e+04]
 

In [28]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
print(X_train)
print("\n")
print(X_test)

[[ 0.58164944 -0.88670699]
 [-0.60673761  1.46173768]
 [-0.01254409 -0.5677824 ]
 [-0.60673761  1.89663484]
 [ 1.37390747 -1.40858358]
 [ 1.47293972  0.99784738]
 [ 0.08648817 -0.79972756]
 [-0.01254409 -0.24885782]
 [-0.21060859 -0.5677824 ]
 [-0.21060859 -0.19087153]
 [-0.30964085 -1.29261101]
 [-0.30964085 -0.5677824 ]
 [ 0.38358493  0.09905991]
 [ 0.8787462  -0.59677555]
 [ 2.06713324 -1.17663843]
 [ 1.07681071 -0.13288524]
 [ 0.68068169  1.78066227]
 [-0.70576986  0.56295021]
 [ 0.77971394  0.35999821]
 [ 0.8787462  -0.53878926]
 [-1.20093113 -1.58254245]
 [ 2.1661655   0.93986109]
 [-0.01254409  1.22979253]
 [ 0.18552042  1.08482681]
 [ 0.38358493 -0.48080297]
 [-0.30964085 -0.30684411]
 [ 0.97777845 -0.8287207 ]
 [ 0.97777845  1.8676417 ]
 [-0.01254409  1.25878567]
 [-0.90383437  2.27354572]
 [-1.20093113 -1.58254245]
 [ 2.1661655  -0.79972756]
 [-1.39899564 -1.46656987]
 [ 0.38358493  2.30253886]
 [ 0.77971394  0.76590222]
 [-1.00286662 -0.30684411]
 [ 0.08648817  0.76590222]
 

In [29]:
# Fitting SVM to the Training set
from sklearn.svm import SVC

classifier = SVC(kernel = "rbf", random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [30]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
print(y_pred)

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1 1 1 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 1 1 1]


In [31]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred))

[[64  4]
 [ 3 29]]


In [32]:
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score

accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Mean: ", accuracies.mean())
print("Std: ", accuracies.std())

Mean:  0.900530218762
Std:  0.0638895735663
